name=input("Hi, Whats your name?")
color=input(f"Hi {name}, Thats dumb. What is your favorite color?")
input("")
print("Ew")
movie=input("What is your favorite movie")
print("Thats garbage")
input("")
print("Whats your favorite class")
input("")
print("Thats a disappointing answer")